### ISSUE TITLE
Endpoint to receive client proven transactions

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#17]
```[tasklist]
### Tasks
- [ ] Add the proto message for the proved transaciton ([ref](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/transaction/proven_tx.rs))
- [ ] Add endpoint `submit_transaction` to rpc.proto and the request/response messages  (additional details https://github.com/0xPolygonMiden/miden-base/discussions/121)
- [ ] Add endpoint `submit_transaction` to mempool.proto and the request/response messages  (additional details https://github.com/0xPolygonMiden/miden-base/discussions/121)
- [ ] Add code to validate the submitted transaction 
```

**Comment by hackaugusto** [comment]
Another assumption that I added above, is that the transaction is saved to the store. Having it on the `mempool` only would make it harder for us to operate the `node` (unexpected restarts would lose data, and graceful restarts would need synchronize the RPC/mempool/provers)

**Comment by bobbinth** [comment]
> An open question about the proof validator. Is it a code component embedded on the RPC server, or is it another server? 

I'm not sure about this yet. In its final form, this component should be simple enough to be a part of the RPC server. However, initially, we'd want to have "training wheels" and as such, the node would re-execute every proven transaction (but not prove it) to make sure they get the same result as is attested by the proof. So, it may make sense to have both, transaction executor and transaction validator be in the same component.

Btw, re-execution is something that we'll enable after v0.1.

**Comment by Dominik1999** [comment]
is this done?

**Comment by hackaugusto** [comment]
> is this done?

Nope, it is not merged yet #85 

https://github.com/0xPolygonMiden/miden-node/pull/85/commits/956b8f64f0513cb01ef2a929eea6b291659260de
