### ISSUE TITLE
Endpoint to receive network transactions

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#18]
```[tasklist]
### Tasks
- [ ] Add the proto message for the prepared transaction ([ref](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/transaction/prepared_tx.rs))
- [ ] Add endpoint `execute_transaction` to rpc.proto and the request/response messages  (additional details https://github.com/0xPolygonMiden/miden-base/discussions/121)
- [ ] Add endpoint `execute_transaction` to store.proto and the request/response messages
- [ ] Add transaction executor.
```

**Comment by hackaugusto** [comment]
For the `miden-base` repo, it seems the executed transaction objects don't have the VM's trace, neither the full data to re-execute the transaction and recover the trace, I could be missing something though.

So for this ticket I assumed the prepared transaction is sent to the server instead. And that is saved in the store. (again, saved in the store because of operational reasons / restarts).

**Comment by bobbinth** [comment]
> For the `miden-base` repo, it seems the executed transaction objects don't have the VM's trace, neither the full data to re-execute the transaction and recover the trace, I could be missing something though.

We now have a [TransactionResult](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/transaction/tx_result.rs) object which can be reduced into [TransactionWitness](https://github.com/0xPolygonMiden/miden-base/blob/main/objects/src/transaction/tx_witness.rs) object. Transaction witness should contain enough data to re-execute and prove a transaction in a stateless manner (i.e., without accessing the data store).

**Comment by bobbinth** [comment]
Closing as no longer relevant. Network transactions will be generated by the node itself rather than received from external sources (or at least that's currently the plan).
