### ISSUE TITLE
Endpoint(s) to retrieve block data

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#20]
```[tasklist]
### Tasks
- [ ] Model the protobuf message corresponding to the block data [ref](https://github.com/0xPolygonMiden/miden-base/tree/main/objects/src/block)
- [ ] Add endpoint to retrieve the data to the store [ref](https://github.com/0xPolygonMiden/miden-base/discussions/121)
- [ ] Add a corresponding endpoint to retrieve the data to the rpc
```

**Comment by hackaugusto** [comment]
Note: There are different design options on the original discussion. The possible versions of the endpoints are [1](https://github.com/0xPolygonMiden/miden-base/discussions/121#discussioncomment-5933367):

- block header only
- compact block (only hashes, no data of notes/accounts)
- full block data (full data of notes/accounts)

The above seems to fit nicely with read masks from [protobuf](https://protobuf.dev/programming-guides/api/#include-field-read-mask)

**Comment by hackaugusto** [comment]
Closing this, since we have `GetBlockHeaderByNumber` and `SyncState`.
