### ISSUE TITLE
Endpoint to retrieve inclusing proofs for notes

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#21]
When proving a transaction, its execution must contain an inclusion proof for the notes it is consuming. This endpoint should help a user to fetch the required data.

```[tasklist]
### Tasks
- [ ] Define a message format for the response data.
- [ ] Define an endpoint for the rpc for the end user.
- [ ] Define an endpoint for the store, to provide the data to the rpc.
```
