### ISSUE TITLE
Endpoint to fetch account data

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#22]
The initial purpose of this endpoint is debugging / validation. The goal is for a user to fetch the data in the rollup, so that it can verify the local and remote data matches.

```[tasklist]
### Tasks
- [ ] Determine the format of the response message
- [ ] Add endpoint to the rpc for the end user
- [ ] Add endpoint to the store for the rpc to request the data
```

**Comment by bobbinth** [comment]
Superseded by #142.
