### ISSUE TITLE
Endpoint to retrieve transaction batch

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#25]
```[tasklist]
### Tasks
- [ ] Add protobuf message to describe the transaction batch
- [ ] Add endpoint to the mempool to be used by the transaction batcher
- [ ] Add transaction batch builder
```

**Comment by bobbinth** [comment]
Closing as this is no longer relevant in the current design.
