### ISSUE TITLE
Batch prover

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#26]
Initial implementation of the batch prover. This component will poll the mempool for batch data, and use a batch kernel to generate a proof of the transaction batch, once done the proof is sent back to the mempool.

```[tasklist]
### Tasks
- [ ] Add new crate/service for the batch prover
- [ ] Create batch kernel
- [ ] Add integration / execution
```
