### ISSUE TITLE
Block producer

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-node#27]
Initial implementation of the block producer. This component will retrieve proven transaction batches from the mempool and generate a block proof.

```[tasklist]
### Tasks
- [ ] Add new crate/component for the block producer
- [ ] Add integration with the mempool, to fetch transaction batches
- [ ] Add block kernel
- [ ] Create the block proofs
- [ ] Add integration with the store, to save the generate block
```

**Comment by bobbinth** [comment]
Closing as this as a part of this is superseded by #33 and batch/block kernels should probably go into separate issues.
