### ISSUE TITLE
Implement initial block producer

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#33]
Write the initial version of the mempool, which only supports proven transactions, builds the transaction batches itself, and sends the transaction batches to the block producer. ~~The mempool will not perform any verification of incoming proven transactions~~.
```[tasklist]
### Tasks
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/35
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/36
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/40
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/41
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/42
```

**Comment by bobbinth** [comment]
A couple of comments:

1. I wonder if `mempool` is the best name and open to suggestions here (other option that comes to minds is `txpool`).
2. Originally, I was imagining the block producer periodically pinging mempool for batches. It could work the other way too (i.e., mempool sending batches to the block producer) - but we should think through the pros/cons of each approach.
3. The mempool will need to some validation of incoming transactions - we'll need to figure out how much exactly though.

**Comment by bobbinth** [comment]
One thing that might be an issue is applying strategies for selecting transactions/batches for the next step. For example, at some point we'd want batch producers to select transactions based on some heuristic (i.e., based on fees and other considerations) and this would mean that batch producers would need to be able to examine the whole transaction queue before picking a set of transactions to work with.

But we can cross this bridge when we get there.

**Comment by Dominik1999** [comment]
Does this issue need to be tracked in "critical path"? We already have #36 and #42 there

**Comment by bobbinth** [comment]
I think this is a "meta issue" to make sure everything else is coming together. We can close it as such - but I also don't see much harm it keeping it open until the basic block producer is up and running.
