### ISSUE TITLE
Txpool: implement block builder task

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-node#36]
```[tasklist]
### Tasks
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/66
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/67
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/68
- [ ] https://github.com/0xPolygonMiden/miden-node/issues/69
```

**Comment by bobbinth** [comment]
Closing this as the only thing remaining is handling of nullifiers for which I'll create a separate issue.
